services:
  open-webui:
    image: ${IMAGE}:${TAG}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${PORT}:8080"
    environment:
      GLOBAL_LOG_LEVEL: "${GLOBAL_LOG_LEVEL:-INFO}"
      OLLAMA_BASE_URL: "${OLLAMA_BASE_URL}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_API_BASE_URLS: "${OPENAI_API_BASE_URLS}"
      PROCESS_IN_BACKGROUND: "false"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: volume
        source: data            # ← reference the key below
        target: /app/backend/data

  docling:
    image: ${DOCLING_IMAGE}:${DOCLING_TAG}
    container_name: ${DOCLING_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${DOCLING_PORT}:5001"
    environment:
      DOCLING_SERVE_ENABLE_UI: "1"
      DOCLING_SERVE_ENABLE_REMOTE_SERVICES: "1"
      DOCLING_SERVE_ARTIFACTS_PATH: ""
      HF_HOME: "${HF_HOME}"
      TRANSFORMERS_CACHE: "${TRANSFORMERS_CACHE}"
      HUGGINGFACE_HUB_TOKEN: "${HUGGINGFACE_HUB_TOKEN:-}"
      HUGGINGFACE_HUB_OFFLINE: "1"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: volume
        source: docling-cache
        target: /opt/app-root/src/.cache
      - type: bind
        source: ./hf-cache
        target: /opt/app-root/src/.cache/huggingface

volumes:
  data:                         # ← YAML key must be static
    name: ${VOLUME_NAME:-open-webui}   # ← actual Docker volume name can use env var
  docling-cache:
